version: "3.9"


services:

  mysql-test:

    image: mysql:8.4


    container_name: ecommerce-mysql-test


    restart: unless-stopped

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: ecommerce_test

      MYSQL_USER: useradmin

      MYSQL_PASSWORD: password123


    ports:

      - "3307:3306"


    volumes:

      - mysql_test_data:/var/lib/mysql


    healthcheck:

      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]

      interval: 10s

      timeout: 5s

      retries: 10



volumes:

  mysql_test_data: